import { PartRequest, TradeCustomer, SystemSettings, SupplierQuotation, SupplierProfile } from "./types";

export const initialSystemSettings: SystemSettings = {
  defaultMarginPercent: 18.0,
  airFreightBaseRateNzd: 185.0,
  seaFreightBaseRateNzd: 65.0,
  gstRate: 0.15,
  requestRefPrefix: "AH-P-",
  autoAssignRoleQueues: true,
  bankAccountDetails: {
    bankName: "ANZ Bank New Zealand Limited",
    accountName: "Autohub New Zealand Limited — Procurly Procurement Trust",
    accountNumber: "06-0801-0498210-00",
    swiftBic: "ANZBNZ22",
  },
};

export const initialSuppliers: SupplierProfile[] = [
  {
    id: "SUP-01",
    name: "Nagoya Auto Direct K.K.",
    country: "Japan",
    currency: "JPY",
    exchangeRateToNzd: 0.0108,
    category: "Japanese OEM Genuine",
    leadTimeDays: 2,
    rating: 4.9,
  },
  {
    id: "SUP-02",
    name: "Osaka EuroTech Spares",
    country: "Japan",
    currency: "JPY",
    exchangeRateToNzd: 0.0108,
    category: "European & JDM Specialist",
    leadTimeDays: 3,
    rating: 4.8,
  },
  {
    id: "SUP-03",
    name: "Trans-Pacific Parts Alliance",
    country: "USA",
    currency: "USD",
    exchangeRateToNzd: 1.68,
    category: "American Truck & SUV",
    leadTimeDays: 4,
    rating: 4.7,
  },
  {
    id: "SUP-04",
    name: "Hanseatic Auto Wholesale GmbH",
    country: "Germany",
    currency: "EUR",
    exchangeRateToNzd: 1.82,
    category: "VAG, BMW, Mercedes Genuine",
    leadTimeDays: 3,
    rating: 4.95,
  },
  {
    id: "SUP-05",
    name: "Australasia Heavy & Commercial Spares",
    country: "Australia",
    currency: "AUD",
    exchangeRateToNzd: 1.10,
    category: "Ute & Commercial Fleet",
    leadTimeDays: 2,
    rating: 4.6,
  },
];

export const initialCustomers: TradeCustomer[] = [
  {
    id: "CUST-001",
    legalBusinessName: "Apex Prestige Motors Limited",
    tradingName: "Apex Motors Auckland",
    nzbn: "9429041234567",
    businessType: "INDEPENDENT_DEALER",
    website: "https://apexmotors.co.nz",
    branchesCount: 2,
    primaryContact: {
      name: "Marcus Vance",
      title: "Procurement & Service Director",
      email: "marcus@apexmotors.co.nz",
      phone: "+64 9 520 1892",
    },
    accountsContact: {
      name: "Clara Jenkins",
      email: "accounts@apexmotors.co.nz",
      phone: "+64 9 520 1893",
    },
    deliveryAddresses: [
      {
        id: "ADDR-1",
        label: "Main Service Center & Workshop",
        street: "42 Great South Road",
        suburb: "Penrose",
        city: "Auckland",
        postcode: "1061",
        isDefault: true,
      },
      {
        id: "ADDR-2",
        label: "North Shore Showroom Depot",
        street: "18 Wairau Road",
        suburb: "Takapuna",
        city: "Auckland",
        postcode: "0627",
        isDefault: false,
      },
    ],
    billingDetails: {
      address: "42 Great South Road, Penrose, Auckland 1061",
      gstNumber: "128-492-381",
      creditRequested: true,
      creditLimitNzd: 25000,
      creditAvailableNzd: 18450,
      paymentTerms: "NET_20TH_MONTH",
      status: "APPROVED",
    },
    compliance: {
      termsVersion: "v2025.1",
      privacyPolicyConsentDate: "2026-01-15T09:30:00Z",
      nzPrivacyActAcknowledged: true,
    },
  },
  {
    id: "CUST-002",
    legalBusinessName: "Canterbury Fleet Maintenance Ltd",
    tradingName: "Canterbury Fleet Services",
    nzbn: "9429038765432",
    businessType: "FLEET_OPERATOR",
    website: "https://canterburyfleet.co.nz",
    branchesCount: 3,
    primaryContact: {
      name: "Hamish Craig",
      title: "Fleet Operations Manager",
      email: "hamish@canterburyfleet.co.nz",
      phone: "+64 3 365 7780",
    },
    accountsContact: {
      name: "Linda Thorne",
      email: "finance@canterburyfleet.co.nz",
      phone: "+64 3 365 7781",
    },
    deliveryAddresses: [
      {
        id: "ADDR-3",
        label: "Christchurch Central Depot",
        street: "112 Blenheim Road",
        suburb: "Riccarton",
        city: "Christchurch",
        postcode: "8041",
        isDefault: true,
      },
    ],
    billingDetails: {
      address: "112 Blenheim Road, Riccarton, Christchurch 8041",
      gstNumber: "099-382-716",
      creditRequested: true,
      creditLimitNzd: 35000,
      creditAvailableNzd: 29500,
      paymentTerms: "NET_20TH_MONTH",
      status: "APPROVED",
    },
    compliance: {
      termsVersion: "v2025.1",
      privacyPolicyConsentDate: "2026-01-20T11:00:00Z",
      nzPrivacyActAcknowledged: true,
    },
  },
  {
    id: "CUST-003",
    legalBusinessName: "Waikato European Specialist Repairs Ltd",
    tradingName: "EuroTech Waikato",
    nzbn: "9429076543210",
    businessType: "MECHANICAL_WORKSHOP",
    branchesCount: 1,
    primaryContact: {
      name: "Stefan Meyer",
      title: "Master Technician & Owner",
      email: "stefan@eurotechwaikato.co.nz",
      phone: "+64 7 839 2100",
    },
    accountsContact: {
      name: "Stefan Meyer",
      email: "stefan@eurotechwaikato.co.nz",
      phone: "+64 7 839 2100",
    },
    deliveryAddresses: [
      {
        id: "ADDR-4",
        label: "Hamilton Workshop",
        street: "88 Te Rapa Road",
        suburb: "Te Rapa",
        city: "Hamilton",
        postcode: "3200",
        isDefault: true,
      },
    ],
    billingDetails: {
      address: "88 Te Rapa Road, Te Rapa, Hamilton 3200",
      gstNumber: "144-892-005",
      creditRequested: false,
      creditLimitNzd: 0,
      creditAvailableNzd: 0,
      paymentTerms: "STRICT_PREPAYMENT",
      status: "PENDING_APPROVAL",
    },
    compliance: {
      termsVersion: "v2025.1",
      privacyPolicyConsentDate: "2026-03-01T14:15:00Z",
      nzPrivacyActAcknowledged: true,
    },
  },
];

export const initialRequests: PartRequest[] = [
  {
    id: "REQ-000123",
    referenceNumber: "AH-P-000123",
    customerId: "CUST-001",
    customerName: "Apex Motors Auckland",
    customerNzbn: "9429041234567",
    customerContactEmail: "marcus@apexmotors.co.nz",
    deliveryAddress: {
      label: "Main Service Center & Workshop",
      street: "42 Great South Road",
      suburb: "Penrose",
      city: "Auckland",
      postcode: "1061",
    },
    submittedDate: "2026-03-02T08:15:00Z",
    updatedDate: "2026-03-03T11:45:00Z",
    status: "AWAITING_PAYMENT",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "JTFLH22P407089123",
      chassisNumber: "TRH200-019842",
      registrationPlate: "MRL849",
      engineCode: "1TR-FE",
      transmission: "AUTOMATIC",
      driveConfiguration: "RWD",
    },
    part: {
      partName: "Left Front Lower Control Arm Assembly with Bushing & Ball Joint",
      oemPartNumber: "48069-26140",
      quantity: 1,
      genuinePreference: "GENUINE_ONLY",
      conditionRequirement: "NEW_GENUINE",
      category: "Suspension & Steering",
      weightEstKg: 6.8,
      descriptionNotes: "Must include factory pressed inner bushings and ball joint. Original part damaged during pothole impact.",
      attachments: [
        {
          name: "damaged_arm_inspection.jpg",
          size: "2.4 MB",
          url: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=600&q=80",
          type: "photo",
        },
        {
          name: "toyota_parts_diagram_front_suspension.pdf",
          size: "640 KB",
          url: "#",
          type: "schematic",
        },
      ],
    },
    supplierQuotes: [
      {
        id: "SQ-101",
        supplierId: "SUP-01",
        supplierName: "Nagoya Auto Direct K.K.",
        supplierCountry: "Japan",
        partCostCurrency: "JPY",
        partCostForeign: 28500,
        exchangeRateToNzd: 0.0108,
        partCostNzd: 307.80,
        domesticFreightForeign: 2500,
        domesticFreightNzd: 27.00,
        availabilityDays: 1,
        notes: "Factory sealed OEM Toyota Japan stock. Immediate dispatch to Nagoya terminal.",
        isRecommendedByAi: true,
      },
      {
        id: "SQ-102",
        supplierId: "SUP-02",
        supplierName: "Osaka EuroTech Spares",
        supplierCountry: "Japan",
        partCostCurrency: "JPY",
        partCostForeign: 31200,
        exchangeRateToNzd: 0.0108,
        partCostNzd: 336.96,
        domesticFreightForeign: 2800,
        domesticFreightNzd: 30.24,
        availabilityDays: 3,
        notes: "Genuine OEM box, slight lead time.",
      },
    ],
    quote: {
      id: "QTE-2026-00123",
      quoteNumber: "QTE-2026-00123",
      createdAt: "2026-03-02T14:30:00Z",
      expiresAt: "2026-03-09T14:30:00Z",
      selectedSupplierQuoteId: "SQ-101",
      basePartCostNzd: 307.80,
      targetMarginPercentage: 18.0,
      marginAmountNzd: 55.40,
      procurementFeeNzd: 45.00,
      landedCostNzd: 334.80,
      freightOptions: [
        {
          method: "AIR_EXPRESS",
          carrierName: "Autohub Air Priority (via Cathay Cargo)",
          estimatedTransitDays: "3 - 5 business days",
          costNzd: 185.00,
          available: true,
        },
        {
          method: "SEA_FREIGHT",
          carrierName: "Autohub Ocean Consolidated (Toyofuji Shipping)",
          estimatedTransitDays: "14 - 18 business days",
          costNzd: 65.00,
          available: true,
        },
      ],
      selectedFreightMethod: "AIR_EXPRESS",
      subtotalNzd: 593.20,
      gstAmountNzd: 88.98,
      totalNzd: 682.18,
      termsAccepted: true,
      status: "ACCEPTED",
    },
    invoice: {
      invoiceNumber: "INV-2026-00891",
      dateIssued: "2026-03-03T11:45:00Z",
      dueDate: "2026-03-05T17:00:00Z",
      customerName: "Apex Prestige Motors Limited",
      customerNzbn: "9429041234567",
      customerGstNumber: "128-492-381",
      billingAddress: "42 Great South Road, Penrose, Auckland 1061",
      paymentMethod: "BANK_TRANSFER",
      paymentReference: "AH-P-000123",
      subtotalNzd: 593.20,
      gstRate: 0.15,
      gstAmountNzd: 88.98,
      totalNzd: 682.18,
      status: "PENDING",
    },
    messages: [
      {
        id: "MSG-1",
        senderId: "CUST-001",
        senderName: "Marcus Vance",
        senderRole: "CUSTOMER",
        timestamp: "2026-03-02T08:15:00Z",
        content: "Hi Autohub team, customer has this vehicle on our hoist. Need OEM genuine arm ASAP. Please price air freight.",
        isInternalOnly: false,
      },
      {
        id: "MSG-2",
        senderId: "STAFF-01",
        senderName: "Nathan Cole",
        senderRole: "SOURCING_SPECIALIST",
        timestamp: "2026-03-02T14:32:00Z",
        content: "Hi Marcus, quote QTE-2026-00123 is now available on your portal. Sourced directly from Toyota Nagoya with 3-5 day air priority transit.",
        isInternalOnly: false,
        isAiGenerated: false,
      },
      {
        id: "MSG-3",
        senderId: "STAFF-01",
        senderName: "Nathan Cole",
        senderRole: "SOURCING_SPECIALIST",
        timestamp: "2026-03-02T14:33:00Z",
        content: "Internal note: Nagoya stock verified in warehouse. Ready to issue PO once customer confirms and finance clears bank transfer.",
        isInternalOnly: true,
      },
    ],
    auditLogs: [
      {
        id: "AUD-1",
        timestamp: "2026-03-02T08:15:00Z",
        actorName: "Marcus Vance",
        actorRole: "CUSTOMER",
        action: "Request Submitted",
        newState: "SUBMITTED",
      },
      {
        id: "AUD-2",
        timestamp: "2026-03-02T09:10:00Z",
        actorName: "System",
        actorRole: "SYSTEM_ADMIN",
        action: "Queue Allocation",
        previousState: "SUBMITTED",
        newState: "SOURCING",
        details: "Assigned to Sourcing Desk queue",
      },
      {
        id: "AUD-3",
        timestamp: "2026-03-02T14:30:00Z",
        actorName: "Nathan Cole",
        actorRole: "SOURCING_SPECIALIST",
        action: "Quote Generated & Issued",
        previousState: "SOURCING",
        newState: "AWAITING_CUSTOMER_APPROVAL",
        details: "Quote QTE-2026-00123 issued with Air and Sea options",
      },
      {
        id: "AUD-4",
        timestamp: "2026-03-03T11:45:00Z",
        actorName: "Marcus Vance",
        actorRole: "CUSTOMER",
        action: "Quote Accepted",
        previousState: "AWAITING_CUSTOMER_APPROVAL",
        newState: "AWAITING_PAYMENT",
        details: "Customer accepted Air Express option ($682.18 NZD incl GST). Tax invoice INV-2026-00891 generated.",
      },
    ],
  },
  {
    id: "REQ-000124",
    referenceNumber: "AH-P-000124",
    customerId: "CUST-001",
    customerName: "Apex Motors Auckland",
    customerNzbn: "9429041234567",
    customerContactEmail: "marcus@apexmotors.co.nz",
    deliveryAddress: {
      label: "North Shore Showroom Depot",
      street: "18 Wairau Road",
      suburb: "Takapuna",
      city: "Auckland",
      postcode: "0627",
    },
    submittedDate: "2026-03-03T09:40:00Z",
    updatedDate: "2026-03-03T15:20:00Z",
    status: "AWAITING_CUSTOMER_APPROVAL",
    vehicle: {
      make: "Mazda",
      model: "CX-5",
      year: 2021,
      vin: "JM0KF4WLA00398124",
      registrationPlate: "NZZ812",
      variant: "Takami AWD 2.5T",
      transmission: "AUTOMATIC",
      driveConfiguration: "AWD",
    },
    part: {
      partName: "Right Front Adaptive LED Headlight Assembly (RHD)",
      oemPartNumber: "KB8B-51-031K",
      quantity: 1,
      genuinePreference: "GENUINE_ONLY",
      conditionRequirement: "NEW_GENUINE",
      category: "Lighting & Electrical",
      weightEstKg: 4.2,
      descriptionNotes: "Must be RHD (New Zealand beam pattern) with adaptive cornering controller.",
    },
    supplierQuotes: [
      {
        id: "SQ-201",
        supplierId: "SUP-01",
        supplierName: "Nagoya Auto Direct K.K.",
        supplierCountry: "Japan",
        partCostCurrency: "JPY",
        partCostForeign: 112000,
        exchangeRateToNzd: 0.0108,
        partCostNzd: 1209.60,
        domesticFreightForeign: 3200,
        domesticFreightNzd: 34.56,
        availabilityDays: 2,
        notes: "Brand new OEM in genuine Mazda crate. Includes integrated LED module.",
        isRecommendedByAi: true,
      },
    ],
    quote: {
      id: "QTE-2026-00124",
      quoteNumber: "QTE-2026-00124",
      createdAt: "2026-03-03T15:20:00Z",
      expiresAt: "2026-03-10T15:20:00Z",
      selectedSupplierQuoteId: "SQ-201",
      basePartCostNzd: 1209.60,
      targetMarginPercentage: 17.5,
      marginAmountNzd: 211.68,
      procurementFeeNzd: 65.00,
      landedCostNzd: 1244.16,
      freightOptions: [
        {
          method: "AIR_EXPRESS",
          carrierName: "Autohub Air Priority",
          estimatedTransitDays: "4 - 6 business days",
          costNzd: 215.00,
          available: true,
        },
        {
          method: "SEA_FREIGHT",
          carrierName: "Autohub Ocean Consolidated",
          estimatedTransitDays: "16 - 20 business days",
          costNzd: 78.00,
          available: true,
        },
      ],
      subtotalNzd: 1701.28,
      gstAmountNzd: 255.19,
      totalNzd: 1956.47,
      termsAccepted: false,
      status: "ISSUED",
    },
    messages: [
      {
        id: "MSG-10",
        senderId: "STAFF-01",
        senderName: "Nathan Cole",
        senderRole: "SOURCING_SPECIALIST",
        timestamp: "2026-03-03T15:22:00Z",
        content: "Quote generated for the genuine RHD CX-5 LED headlamp. Verified Japanese Domestic Market beam geometry for NZ WOF compliance.",
        isInternalOnly: false,
      },
    ],
    auditLogs: [
      {
        id: "AUD-10",
        timestamp: "2026-03-03T09:40:00Z",
        actorName: "Marcus Vance",
        actorRole: "CUSTOMER",
        action: "Request Submitted",
        newState: "SUBMITTED",
      },
      {
        id: "AUD-11",
        timestamp: "2026-03-03T15:20:00Z",
        actorName: "Nathan Cole",
        actorRole: "SOURCING_SPECIALIST",
        action: "Quote Issued",
        previousState: "SOURCING",
        newState: "AWAITING_CUSTOMER_APPROVAL",
      },
    ],
  },
  {
    id: "REQ-000125",
    referenceNumber: "AH-P-000125",
    customerId: "CUST-002",
    customerName: "Canterbury Fleet Services",
    customerNzbn: "9429038765432",
    customerContactEmail: "hamish@canterburyfleet.co.nz",
    deliveryAddress: {
      label: "Christchurch Central Depot",
      street: "112 Blenheim Road",
      suburb: "Riccarton",
      city: "Christchurch",
      postcode: "8041",
    },
    submittedDate: "2026-02-25T11:00:00Z",
    updatedDate: "2026-03-04T07:15:00Z",
    status: "IN_TRANSIT",
    vehicle: {
      make: "Ford",
      model: "Ranger",
      year: 2022,
      vin: "MPBUMFF50NX182901",
      registrationPlate: "PKD774",
      engineCode: "2.0L EcoBlue Bi-Turbo",
      variant: "Wildtrak 4x4",
      transmission: "AUTOMATIC",
      driveConfiguration: "4WD",
    },
    part: {
      partName: "Garrett Bi-Turbocharger Assembly with Actuators & Gasket Kit",
      oemPartNumber: "JB3Q-6K682-PB",
      quantity: 1,
      genuinePreference: "GENUINE_ONLY",
      conditionRequirement: "NEW_GENUINE",
      category: "Engine & Drivetrain",
      weightEstKg: 14.5,
    },
    supplierQuotes: [
      {
        id: "SQ-301",
        supplierId: "SUP-05",
        supplierName: "Australasia Heavy & Commercial Spares",
        supplierCountry: "Australia",
        partCostCurrency: "AUD",
        partCostForeign: 2450,
        exchangeRateToNzd: 1.10,
        partCostNzd: 2695.00,
        domesticFreightForeign: 85,
        domesticFreightNzd: 93.50,
        availabilityDays: 1,
        notes: "In Melbourne warehouse, ready to air freight.",
      },
    ],
    quote: {
      id: "QTE-2026-00125",
      quoteNumber: "QTE-2026-00125",
      createdAt: "2026-02-26T09:00:00Z",
      expiresAt: "2026-03-05T09:00:00Z",
      selectedSupplierQuoteId: "SQ-301",
      basePartCostNzd: 2695.00,
      targetMarginPercentage: 15.0,
      marginAmountNzd: 404.25,
      procurementFeeNzd: 95.00,
      landedCostNzd: 2788.50,
      freightOptions: [
        {
          method: "AIR_EXPRESS",
          carrierName: "Qantas Freight / Air New Zealand Cargo",
          estimatedTransitDays: "2 - 4 business days",
          costNzd: 265.00,
          available: true,
        },
      ],
      selectedFreightMethod: "AIR_EXPRESS",
      subtotalNzd: 3459.25,
      gstAmountNzd: 518.89,
      totalNzd: 3978.14,
      termsAccepted: true,
      status: "ACCEPTED",
    },
    invoice: {
      invoiceNumber: "INV-2026-00850",
      receiptNumber: "REC-2026-00850",
      dateIssued: "2026-02-26T14:10:00Z",
      dueDate: "2026-03-20T17:00:00Z",
      paidDate: "2026-02-27T10:00:00Z",
      customerName: "Canterbury Fleet Maintenance Ltd",
      customerNzbn: "9429038765432",
      customerGstNumber: "099-382-716",
      billingAddress: "112 Blenheim Road, Riccarton, Christchurch 8041",
      paymentMethod: "TRADE_CREDIT",
      paymentReference: "AH-P-000125",
      subtotalNzd: 3459.25,
      gstRate: 0.15,
      gstAmountNzd: 518.89,
      totalNzd: 3978.14,
      status: "PAID",
    },
    shipment: {
      id: "SHP-00125",
      carrier: "DHL Express Global / Qantas Freight",
      trackingNumber: "DHL-NZ-982341990",
      originPort: "Melbourne International Airport (MEL)",
      destinationPort: "Christchurch International Airport (CHC)",
      vesselOrFlightNumber: "QF0133",
      customsEntryNumber: "NZ-CUS-2026-89412",
      etd: "2026-03-03T18:00:00Z",
      eta: "2026-03-05T14:30:00Z",
      milestones: [
        {
          id: "M-1",
          stage: "Supplier Dispatched",
          status: "SUPPLIER_DISPATCHED",
          timestamp: "2026-03-01T10:30:00Z",
          location: "Melbourne, Australia",
          notes: "Collected by carrier from supplier warehouse",
          completed: true,
        },
        {
          id: "M-2",
          stage: "Received At Shipping Facility",
          status: "RECEIVED_AT_SHIPPING_FACILITY",
          timestamp: "2026-03-02T14:00:00Z",
          location: "Autohub Melbourne Air Logistics Hub",
          notes: "Repackaged with reinforced crate and export barcode applied",
          completed: true,
        },
        {
          id: "M-3",
          stage: "In Transit (Flight Departed)",
          status: "IN_TRANSIT",
          timestamp: "2026-03-04T07:15:00Z",
          location: "En Route Trans-Tasman (QF0133)",
          notes: "Cargo manifested on Qantas freight service to CHC",
          completed: true,
        },
        {
          id: "M-4",
          stage: "Arrived In New Zealand",
          status: "ARRIVED_IN_NZ",
          timestamp: "2026-03-05T14:30:00Z",
          location: "Christchurch Airport Air Cargo Terminal",
          completed: false,
        },
        {
          id: "M-5",
          stage: "Customs Clearance",
          status: "CUSTOMS_CLEARANCE",
          timestamp: "2026-03-05T16:00:00Z",
          location: "NZ Customs Service CHC",
          completed: false,
        },
        {
          id: "M-6",
          stage: "Out For Delivery",
          status: "OUT_FOR_DELIVERY",
          timestamp: "2026-03-06T08:00:00Z",
          location: "Christchurch Local Express",
          completed: false,
        },
        {
          id: "M-7",
          stage: "Delivered",
          status: "DELIVERED",
          timestamp: "2026-03-06T11:00:00Z",
          location: "Riccarton Workshop",
          completed: false,
        },
      ],
    },
    messages: [
      {
        id: "MSG-20",
        senderId: "STAFF-02",
        senderName: "Liam Patel",
        senderRole: "LOGISTICS_COORDINATOR",
        timestamp: "2026-03-04T07:20:00Z",
        content: "Good morning Hamish, the Ranger bi-turbo is onboard flight QF0133 from Melbourne. Expected arrival at CHC this afternoon.",
        isInternalOnly: false,
      },
    ],
    auditLogs: [
      {
        id: "AUD-20",
        timestamp: "2026-02-25T11:00:00Z",
        actorName: "Hamish Craig",
        actorRole: "CUSTOMER",
        action: "Request Submitted",
        newState: "SUBMITTED",
      },
      {
        id: "AUD-21",
        timestamp: "2026-02-27T10:00:00Z",
        actorName: "Finance Officer",
        actorRole: "FINANCE_OFFICER",
        action: "Trade Credit Approved & Deducted",
        previousState: "AWAITING_PAYMENT",
        newState: "PAYMENT_CONFIRMED",
      },
      {
        id: "AUD-22",
        timestamp: "2026-03-04T07:15:00Z",
        actorName: "Liam Patel",
        actorRole: "LOGISTICS_COORDINATOR",
        action: "Shipment Departed Origin",
        previousState: "RECEIVED_AT_SHIPPING_FACILITY",
        newState: "IN_TRANSIT",
      },
    ],
  },
  {
    id: "REQ-000126",
    referenceNumber: "AH-P-000126",
    customerId: "CUST-001",
    customerName: "Apex Motors Auckland",
    customerNzbn: "9429041234567",
    customerContactEmail: "marcus@apexmotors.co.nz",
    deliveryAddress: {
      label: "Main Service Center & Workshop",
      street: "42 Great South Road",
      suburb: "Penrose",
      city: "Auckland",
      postcode: "1061",
    },
    submittedDate: "2026-02-20T10:30:00Z",
    updatedDate: "2026-03-04T09:00:00Z",
    status: "CUSTOMS_CLEARANCE",
    vehicle: {
      make: "Nissan",
      model: "Leaf",
      year: 2020,
      vin: "JN1AZ1CP6L0091823",
      registrationPlate: "NWT290",
      variant: "e+ 62kWh Tekna",
    },
    part: {
      partName: "EV Power Delivery Module (PDM) Inverter & On-Board Charger",
      oemPartNumber: "292C0-5SA0A",
      quantity: 1,
      genuinePreference: "GENUINE_ONLY",
      conditionRequirement: "RECONDITIONED_OEM",
      category: "EV Powertrain",
      weightEstKg: 18.0,
    },
    supplierQuotes: [
      {
        id: "SQ-401",
        supplierId: "SUP-01",
        supplierName: "Nagoya Auto Direct K.K.",
        supplierCountry: "Japan",
        partCostCurrency: "JPY",
        partCostForeign: 185000,
        exchangeRateToNzd: 0.0108,
        partCostNzd: 1998.00,
        domesticFreightForeign: 4500,
        domesticFreightNzd: 48.60,
        availabilityDays: 3,
        notes: "Factory bench tested & reprogrammed with latest firmware.",
      },
    ],
    quote: {
      id: "QTE-2026-00126",
      quoteNumber: "QTE-2026-00126",
      createdAt: "2026-02-21T11:00:00Z",
      expiresAt: "2026-02-28T11:00:00Z",
      selectedSupplierQuoteId: "SQ-401",
      basePartCostNzd: 1998.00,
      targetMarginPercentage: 16.0,
      marginAmountNzd: 319.68,
      procurementFeeNzd: 80.00,
      landedCostNzd: 2046.60,
      freightOptions: [
        {
          method: "AIR_EXPRESS",
          carrierName: "Air New Zealand Cargo",
          estimatedTransitDays: "4 - 5 business days",
          costNzd: 290.00,
          available: true,
        },
      ],
      selectedFreightMethod: "AIR_EXPRESS",
      subtotalNzd: 2687.68,
      gstAmountNzd: 403.15,
      totalNzd: 3090.83,
      termsAccepted: true,
      status: "ACCEPTED",
    },
    invoice: {
      invoiceNumber: "INV-2026-00821",
      receiptNumber: "REC-2026-00821",
      dateIssued: "2026-02-21T15:00:00Z",
      dueDate: "2026-03-20T17:00:00Z",
      paidDate: "2026-02-22T09:00:00Z",
      customerName: "Apex Prestige Motors Limited",
      customerNzbn: "9429041234567",
      customerGstNumber: "128-492-381",
      billingAddress: "42 Great South Road, Penrose, Auckland 1061",
      paymentMethod: "TRADE_CREDIT",
      paymentReference: "AH-P-000126",
      subtotalNzd: 2687.68,
      gstRate: 0.15,
      gstAmountNzd: 403.15,
      totalNzd: 3090.83,
      status: "PAID",
    },
    shipment: {
      id: "SHP-00126",
      carrier: "Mainfreight Air & Ocean / DHL",
      trackingNumber: "MF-AKL-20269411",
      originPort: "Centrair Nagoya (NGO)",
      destinationPort: "Auckland International Airport (AKL)",
      vesselOrFlightNumber: "NZ0090",
      customsEntryNumber: "NZ-CUS-2026-77120",
      etd: "2026-02-28T21:00:00Z",
      eta: "2026-03-04T06:30:00Z",
      milestones: [
        {
          id: "M-1",
          stage: "Arrived In New Zealand",
          status: "ARRIVED_IN_NZ",
          timestamp: "2026-03-04T06:30:00Z",
          location: "Auckland Airport Cargo Hub",
          notes: "Flight NZ0090 touched down. Unloaded to bond store.",
          completed: true,
        },
        {
          id: "M-2",
          stage: "Customs Clearance & MPI Bio-Security",
          status: "CUSTOMS_CLEARANCE",
          timestamp: "2026-03-04T09:00:00Z",
          location: "NZ Customs Service / MPI Auckland",
          notes: "Tariff code 8504.40 approved. Awaiting final green line clearance.",
          completed: true,
        },
        {
          id: "M-3",
          stage: "Out For Delivery",
          status: "OUT_FOR_DELIVERY",
          timestamp: "2026-03-05T08:30:00Z",
          location: "Auckland Metro Courier",
          completed: false,
        },
      ],
    },
    messages: [
      {
        id: "MSG-30",
        senderId: "STAFF-02",
        senderName: "Liam Patel",
        senderRole: "LOGISTICS_COORDINATOR",
        timestamp: "2026-03-04T09:05:00Z",
        content: "Hi Marcus, the Leaf PDM inverter has landed at AKL and is undergoing standard MPI/Customs clearance today. Should dispatch to your Penrose workshop tomorrow morning.",
        isInternalOnly: false,
      },
    ],
    auditLogs: [
      {
        id: "AUD-30",
        timestamp: "2026-03-04T09:00:00Z",
        actorName: "Liam Patel",
        actorRole: "LOGISTICS_COORDINATOR",
        action: "Customs Clearance Lodged",
        newState: "CUSTOMS_CLEARANCE",
      },
    ],
  },
  {
    id: "REQ-000127",
    referenceNumber: "AH-P-000127",
    customerId: "CUST-002",
    customerName: "Canterbury Fleet Services",
    customerNzbn: "9429038765432",
    customerContactEmail: "hamish@canterburyfleet.co.nz",
    deliveryAddress: {
      label: "Christchurch Central Depot",
      street: "112 Blenheim Road",
      suburb: "Riccarton",
      city: "Christchurch",
      postcode: "8041",
    },
    submittedDate: "2026-03-04T08:00:00Z",
    updatedDate: "2026-03-04T08:05:00Z",
    status: "SOURCING",
    vehicle: {
      make: "Subaru",
      model: "Outback",
      year: 2023,
      vin: "JF2BT9EC5PH019842",
      registrationPlate: "QAB118",
      engineCode: "FB25DI 2.5L",
      transmission: "CVT",
      driveConfiguration: "AWD",
    },
    part: {
      partName: "Electronic Power Steering Rack & Pinion Assembly with Tie Rods",
      oemPartNumber: "34110-AN00A",
      quantity: 1,
      genuinePreference: "GENUINE_ONLY",
      conditionRequirement: "NEW_GENUINE",
      category: "Suspension & Steering",
      weightEstKg: 12.0,
      descriptionNotes: "Customer hit a curb during snow event. Must be factory brand new OEM.",
    },
    supplierQuotes: [],
    messages: [
      {
        id: "MSG-40",
        senderId: "CUST-002",
        senderName: "Hamish Craig",
        senderRole: "CUSTOMER",
        timestamp: "2026-03-04T08:00:00Z",
        content: "Need this Subaru steering rack priced urgent please. Let me know JDM vs local availability.",
        isInternalOnly: false,
      },
    ],
    auditLogs: [
      {
        id: "AUD-40",
        timestamp: "2026-03-04T08:00:00Z",
        actorName: "Hamish Craig",
        actorRole: "CUSTOMER",
        action: "Request Submitted",
        newState: "SUBMITTED",
      },
      {
        id: "AUD-41",
        timestamp: "2026-03-04T08:05:00Z",
        actorName: "System",
        actorRole: "SYSTEM_ADMIN",
        action: "Status Updated",
        previousState: "SUBMITTED",
        newState: "SOURCING",
      },
    ],
  },
  {
    id: "REQ-000128",
    referenceNumber: "AH-P-000128",
    customerId: "CUST-001",
    customerName: "Apex Motors Auckland",
    customerNzbn: "9429041234567",
    customerContactEmail: "marcus@apexmotors.co.nz",
    deliveryAddress: {
      label: "Main Service Center & Workshop",
      street: "42 Great South Road",
      suburb: "Penrose",
      city: "Auckland",
      postcode: "1061",
    },
    submittedDate: "2026-02-10T14:20:00Z",
    updatedDate: "2026-02-28T16:00:00Z",
    status: "DELIVERED",
    vehicle: {
      make: "Isuzu",
      model: "D-Max",
      year: 2018,
      vin: "MPATFS85JJT091238",
      registrationPlate: "LGT340",
      variant: "LS 4x4 Double Cab",
    },
    part: {
      partName: "Rear Tailgate Complete Assembly with Handle & Reverse Camera Housing",
      oemPartNumber: "8-98248571-0",
      quantity: 1,
      genuinePreference: "AFTERMARKET_ACCEPTABLE",
      conditionRequirement: "NEW_AFTERMARKET",
      category: "Body & Exterior",
      weightEstKg: 22.0,
    },
    supplierQuotes: [
      {
        id: "SQ-501",
        supplierId: "SUP-05",
        supplierName: "Australasia Heavy & Commercial Spares",
        supplierCountry: "Australia",
        partCostCurrency: "AUD",
        partCostForeign: 680,
        exchangeRateToNzd: 1.10,
        partCostNzd: 748.00,
        domesticFreightForeign: 45,
        domesticFreightNzd: 49.50,
        availabilityDays: 1,
      },
    ],
    quote: {
      id: "QTE-2026-00128",
      quoteNumber: "QTE-2026-00128",
      createdAt: "2026-02-11T10:00:00Z",
      expiresAt: "2026-02-18T10:00:00Z",
      selectedSupplierQuoteId: "SQ-501",
      basePartCostNzd: 748.00,
      targetMarginPercentage: 18.0,
      marginAmountNzd: 134.64,
      procurementFeeNzd: 50.00,
      landedCostNzd: 797.50,
      freightOptions: [
        {
          method: "SEA_FREIGHT",
          carrierName: "Autohub Trans-Tasman Ocean Express",
          estimatedTransitDays: "12 - 14 business days",
          costNzd: 120.00,
          available: true,
        },
      ],
      selectedFreightMethod: "SEA_FREIGHT",
      subtotalNzd: 1052.64,
      gstAmountNzd: 157.90,
      totalNzd: 1210.54,
      termsAccepted: true,
      status: "ACCEPTED",
    },
    invoice: {
      invoiceNumber: "INV-2026-00780",
      receiptNumber: "REC-2026-00780",
      dateIssued: "2026-02-12T09:00:00Z",
      dueDate: "2026-03-20T17:00:00Z",
      paidDate: "2026-02-12T14:30:00Z",
      customerName: "Apex Prestige Motors Limited",
      customerNzbn: "9429041234567",
      customerGstNumber: "128-492-381",
      billingAddress: "42 Great South Road, Penrose, Auckland 1061",
      paymentMethod: "TRADE_CREDIT",
      paymentReference: "AH-P-000128",
      subtotalNzd: 1052.64,
      gstRate: 0.15,
      gstAmountNzd: 157.90,
      totalNzd: 1210.54,
      status: "PAID",
    },
    shipment: {
      id: "SHP-00128",
      carrier: "Mainfreight New Zealand",
      trackingNumber: "MF-NZ-8891230",
      originPort: "Port of Brisbane (BNE)",
      destinationPort: "Ports of Auckland (AKL)",
      vesselOrFlightNumber: "Pacific Trader v.208",
      customsEntryNumber: "NZ-CUS-2026-55910",
      etd: "2026-02-14T08:00:00Z",
      eta: "2026-02-27T17:00:00Z",
      actualDeliveryDate: "2026-02-28T15:45:00Z",
      podSignatureUrl: "#",
      milestones: [
        {
          id: "M-1",
          stage: "Delivered",
          status: "DELIVERED",
          timestamp: "2026-02-28T15:45:00Z",
          location: "Apex Motors Penrose Workshop",
          notes: "Signed by D. Campbell at goods inwards. No transit damage reported.",
          completed: true,
        },
      ],
    },
    messages: [
      {
        id: "MSG-50",
        senderId: "STAFF-02",
        senderName: "Liam Patel",
        senderRole: "LOGISTICS_COORDINATOR",
        timestamp: "2026-02-28T16:00:00Z",
        content: "Package delivered and signed for at Penrose depot. Thank you for procuring through Autohub!",
        isInternalOnly: false,
      },
    ],
    auditLogs: [
      {
        id: "AUD-50",
        timestamp: "2026-02-28T15:45:00Z",
        actorName: "Liam Patel",
        actorRole: "LOGISTICS_COORDINATOR",
        action: "Order Delivered",
        previousState: "OUT_FOR_DELIVERY",
        newState: "DELIVERED",
      },
    ],
  },
];
